/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/generics/AppLoading.vue')['default']
    BaseLayout: typeof import('./../components/layouts/BaseLayout.vue')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
