/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoading: typeof import('./../components/generics/AppLoading.vue')['default']
    AuthLayout: typeof import('./../components/layouts/AuthLayout.vue')['default']
    GuestLayout: typeof import('./../components/layouts/GuestLayout.vue')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PublicLayout: typeof import('./../components/layouts/PublicLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
